project: 
  type: website

resources:
  - data/AugustoSI_allelefrequencies.csv
  
website: 
  page-navigation: true
  title: "Making sharable documents with Quarto" 
  site-url: "https://gkutlerdodd.github.io/immunobiology-computer-exercises" 
  repo-url: https://github.com/gkutlerdodd/immunobiology-computer-exercises
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Theoretical Biology & Bioinformatics, Utrecht University"
    
  sidebar:  
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Crossreactivity

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true

filters:
  - include-files.lua
  - quarto

  
